apiVersion: v1alpha
kind: espresso
sauce:
  region: us-west-1
  concurrency: 10
  retries: ${RETRIES}
  metadata:
    tags:
      - e2e
    build: Release
espresso:
  app: ./apps/mda-1.0.10-12.apk
  testApp: ./apps/mda-androidTest-1.0.10-12.apk
suites:
  - name: "Test Demo App"
    passThreshold: ${PASS_THRESHOLD}
    emulators:
      - name: "${EMULATOR}"
        platformVersions:
          - "${ANDROID_VERSION}"
artifacts:
  download:
    when: always
    match:
      - junit.xml
    directory: ./artifacts/

reporters:
  spotlight: # Prints an overview of failed or otherwise interesting jobs.
    enabled: true
